apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels:
        app: fastapi-ml
    spec:
      containers:
        - image: rchermanteev/2020_made_ml_in_production:v2
          name: fastapi-ml
          ports:
            - containerPort: 5000
