apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-resourses
  labels:
    app: fastapi-ml-resourses
spec:
  containers:
    - image: rchermanteev/2020_made_ml_in_production
      name: fastapi-ml
      ports:
        - containerPort: 5000
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
