test_data_path: "data/raw/test.csv"
output_model_path: "models/model_logistic_regression.pkl"
predicts_path: "models/predicts_logistic_regression.csv"
transformer_params_path: "models/transformer_params.pkl"
logging_config_path: "configs/logging.conf.yml"
