version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s:%(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  file_handler:
    class: logging.FileHandler
    filename: ml_project.log
    level: INFO
    formatter: simple
  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: DEBUG
    formatter: simple
loggers:
  ml_project:
    level: DEBUG
    handlers: [file_handler, stream_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [stream_handler]